spring:
  data:
    mongodb:
      uri: mongodb+srv://user:user@cluster0.gw7id.mongodb.net/qrnotify?retryWrites=true&w=majority
server:
  port: 8080
chen:
  base_path: /nebrija/qrnotify-pruebas

qrnotify:
  broker:
    host: ssl://80iqd8.stackhero-network.com:8883
    user: admin
    password: iRgOP5bibBMsFsuHDtI8I8yPNhSlC0th
    cert: src/main/resources/certifications/ca.pem
